# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvboEJxPUi1QjSiIoxUG7JJilY33B0Ba
"""

!pip install gradio transformers --quiet

import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load a publicly available model from Hugging Face
MODEL_NAME = "distilgpt2" # Changed to a publicly available model that does not require authentication
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)

# Prompt templates for demographic adaptation
PROMPT_TEMPLATES = {
    "Student": "You are a friendly AI finance assistant for students. Use simple, motivating language and focus on budgeting, saving, and beginner investments.\n\nUser: {query}",
    "Professional": "You are an expert finance assistant for professionals. Use a formal tone, provide detailed advice on taxes, investments, and advanced budgeting.\n\nUser: {query}"
}

# Function to generate response
def chatbot(user_query, user_type, income, expenses, investment_goals):
    # Combine profile info
    profile_info = f"User type: {user_type}\nMonthly Income: {income}\nMonthly Expenses: ₹{expenses}\nInvestment Goals: {investment_goals}\n"
    # Generate budget summary
    savings = income - expenses
    budget_summary = f"Monthly Income: ₹{income}\nMonthly Expenses: ₹{expenses}\nEstimated Savings: ₹{savings}\n"
    # Demographic-aware prompt
    prompt = PROMPT_TEMPLATES[user_type].format(query=f"{profile_info}{user_query}")
    # Get model response
    input_ids = tokenizer.encode(prompt, return_tensors="pt", truncation=True)
    output = model.generate(input_ids, max_length=350, pad_token_id=tokenizer.eos_token_id)
    answer = tokenizer.decode(output[0], skip_special_tokens=True).split("User:",1)[-1].strip()
    # Spending Insights
    suggestions = ""
    if savings < 0:
        suggestions = "Your expenses exceed your income. Try to cut down on discretionary spending and review subscriptions."
    elif savings < (0.2 * income):
        suggestions = "Good job saving, but aim for at least 20% savings. Reduce unnecessary expenses for financial health."
    else:
        suggestions = "Excellent savings! Consider investing more towards your stated goals."
    # Combine all outputs
    resp = f"{answer}\n\n---\n**Budget Summary:**\n{budget_summary}\n**Spending Insights:** {suggestions}"
    return resp

# Create Gradio app
iface = gr.Interface(
    fn=chatbot,
    inputs=[
        gr.Textbox(lines=2, label="Ask your finance question:"),
        gr.Radio(choices=["Student", "Professional"], label="Select user type"),
        gr.Number(label="Monthly Income (₹)", value=30000),
        gr.Number(label="Monthly Expenses (₹)", value=20000),
        gr.Textbox(label="Investment Goals (e.g. save for house, retirement)")
    ],
    outputs="markdown",
    title="FinanceGenie: Intelligent Personal Finance Chatbot",
    description="AI-powered guidance for savings, taxes, investments, and budgeting. Adapts advice for students and professionals.",
    theme="default"
)

iface.launch(share=True)

import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load a publicly available model from Hugging Face
MODEL_NAME = "distilgpt2" # Changed to a publicly available model that does not require authentication
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)

# Prompt templates for demographic adaptation
PROMPT_TEMPLATES = {
    "Student": "You are a friendly AI finance assistant for students. Use simple, motivating language and focus on budgeting, saving, and beginner investments.\n\nUser: {query}",
    "Professional": "You are an expert finance assistant for professionals. Use a formal tone, provide detailed advice on taxes, investments, and advanced budgeting.\n\nUser: {query}"
}

# Function to generate response
def finance_chatbot(user_query, user_type, income, expenses, goals):
    # Prepare demographic-aware prompt (single mention)
    prompt = (
        f"You are a finance chatbot helping a {user_type}.\n"
        f"The user has a monthly income of ₹{income} and monthly expenses of ₹{expenses}.\n"
        f"Investment goals: {goals}\n"
        f"Question: {user_query}\n"
        "Provide personalized advice, a budget summary, and actionable spending insights."
    )

    input_ids = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(input_ids, max_length=220, pad_token_id=tokenizer.eos_token_id)
    reply = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Optional: Remove repeated sentences like "I am a student"
    # Keep only the most relevant first chunk
    cleaned_reply = []
    for line in reply.split('\n'):
        if "I am a student" not in line.strip():
            cleaned_reply.append(line)
    reply = '\n'.join(cleaned_reply).strip()

    # Budget logic as before
    savings = income - expenses
    budget = f"Monthly Income: ₹{income}\nMonthly Expenses: ₹{expenses}\nEstimated Savings: ₹{savings}"
    if savings < 0:
        suggestion = "Your expenses exceed your income. Try to cut down on unnecessary spending."
    elif savings < income * 0.2:
        suggestion = "Try aiming for at least 20% savings. Review discretionary spending."
    else:
        suggestion = "Excellent savings! Consider investing more towards your stated goals."

    return f"{reply}\n\n---\n**Budget Summary:**\n{budget}\n**Spending Insights:** {suggestion}"



# Create Gradio app
iface = gr.Interface(
    fn=chatbot,
    inputs=[
        gr.Textbox(lines=2, label="Ask your finance question:"),
        gr.Radio(choices=["Student", "Professional"], label="Select user type"),
        gr.Number(label="Monthly Income (₹)", value=30000),
        gr.Number(label="Monthly Expenses (₹)", value=20000),
        gr.Textbox(label="Investment Goals (e.g. save for house, retirement)")
    ],
    outputs="markdown",
    title="FinanceGenie: Intelligent Personal Finance Chatbot",
    description="AI-powered guidance for savings, taxes, investments, and budgeting. Adapts advice for students and professionals.",
    theme="default"
)

iface.launch(share=True)

def finance_chatbot(user_query, user_type, income, expenses, goals):
    # Prepare demographic-aware prompt (single mention)
    prompt = (
        f"You are a finance chatbot helping a {user_type}.\n"
        f"The user has a monthly income of ₹{income} and monthly expenses of ₹{expenses}.\n"
        f"Investment goals: {goals}\n"
        f"Question: {user_query}\n"
        "Provide personalized advice, a budget summary, and actionable spending insights."
    )

    input_ids = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(input_ids, max_length=220, pad_token_id=tokenizer.eos_token_id)
    reply = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Optional: Remove repeated sentences like "I am a student"
    # Keep only the most relevant first chunk
    cleaned_reply = []
    for line in reply.split('\n'):
        if "I am a student" not in line.strip():
            cleaned_reply.append(line)
    reply = '\n'.join(cleaned_reply).strip()

    # Budget logic as before
    savings = income - expenses
    budget = f"Monthly Income: ₹{income}\nMonthly Expenses: ₹{expenses}\nEstimated Savings: ₹{savings}"
    if savings < 0:
        suggestion = "Your expenses exceed your income. Try to cut down on unnecessary spending."
    elif savings < income * 0.2:
        suggestion = "Try aiming for at least 20% savings. Review discretionary spending."
    else:
        suggestion = "Excellent savings! Consider investing more towards your stated goals."

    return f"{reply}\n\n---\n**Budget Summary:**\n{budget}\n**Spending Insights:** {suggestion}"